name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Setting up 
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: |
          [{
            "id": "knowage-group",
            "username": "${{ secrets.KNOWAGE_NEXUS_USERNAME }}",
            "password": "${{ secrets.KNOWAGE_NEXUS_PASSWORD }}"
          }]
        mirrors: |
          [{
            "id": "knowage-group",
            "name": "KNOWAGE Nexus",
            "mirrorOf": "*",
            "url": "${{ vars.KNOWAGE_NEXUS_URL_KNOWAGE_GROUP }}"
          }]

    - name: Build
      run: mvn compile -f knowage-ce-parent/pom.xml
